### ISSUE TITLE
较大数据规模下All-NaN slice问题

### ISSUE THREAD

**Issue by zhaoyiming808** [UePG-21/gpquant#10]
``` python3
sr.fit(df.iloc[:508], df["C"].iloc[:508])
```

Traceback (most recent call last):
  File "C:\Users\lpoem\PycharmProjects\factor_mining\main.py", line 44, in <module>
    sr.fit(df.iloc[:508], df["C"].iloc[:508])
  File "C:\Users\lpoem\PycharmProjects\factor_mining\.venv\Lib\site-packages\gpquant\SymbolicRegressor.py", line 144, in fit
    self.__evolve()
  File "C:\Users\lpoem\PycharmProjects\factor_mining\.venv\Lib\site-packages\gpquant\SymbolicRegressor.py", line 106, in __evolve
    parent = self.__tournament()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lpoem\PycharmProjects\factor_mining\.venv\Lib\site-packages\gpquant\SymbolicRegressor.py", line 87, in __tournament
    parent_index = contenders[np.nanargmax(fitness)]
                              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lpoem\PycharmProjects\factor_mining\.venv\Lib\site-packages\numpy\lib\nanfunctions.py", line 613, in nanargmax
    raise ValueError("All-NaN slice encountered")
ValueError: All-NaN slice encountered

``` python3
def __tournament(self) -> SyntaxTree:
    contenders = random.sample(range(self.population_size), self.tournament_size)
    fitness = [self.fitness[i] for i in contenders]
    if self.metric.sign > 0:
        parent_index = contenders[np.nanargmax(fitness)]
    else:
        parent_index = contenders[np.nanargmin(fitness)]
    return self.trees[parent_index]
```
__tournament()函数似乎在较大数据规模下会出现fitness元素全为NaN的问题，不知道问题出在哪？可以请帮忙看一下是哪的问题？

**Comment by UePG-21** [comment]
可能是lookback window遗传出来太大了，我从这看不出具体问题，你还是要一步一步debug一下

**Comment by lpoems007** [comment]
> 可能是lookback window遗传出来太大了，我从这看不出具体问题，你还是要一步一步debug一下

噢噢，谢谢回复，我试了一下就有些很少的情况才会出现fitness全为nan的问题，要不直接改成if self.metric.sign > 0 or not all(pd.isna(fitness))？
