### ISSUE TITLE
import SymbolicRegressor failed

### ISSUE THREAD

**Issue by baikai** [UePG-21/gpquant#3]
In centos server (CentOS Linux release 7.9.2009) and python 3.8 environment, import SymbolicRegressor failed.
Error details like below:
[baikai@localhost gp]$ python3
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gpquant.SymbolicRegressor import SymbolicRegressor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/baikai/.local/lib/python3.8/site-packages/gpquant/SymbolicRegressor.py", line 10, in <module>
    from .SyntaxTree import SyntaxTree
  File "/home/baikai/.local/lib/python3.8/site-packages/gpquant/SyntaxTree.py", line 61, in <module>
    class SyntaxTree:
  File "/home/baikai/.local/lib/python3.8/site-packages/gpquant/SyntaxTree.py", line 173, in SyntaxTree
    def __flatten(self) -> list[Node]:
TypeError: 'type' object is not subscriptable

**Comment by UePG-21** [comment]
Python 3.8 does not support type hint like list[int]. Please try at least 3.9.

**Comment by baikai** [comment]
thx for your comments
